import NotificationBar from '@/components/layout/NotificationBar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/layout/Footer'
import Navbar from '@/components/layout/Navbar'
import Providers from '@/components/providers/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NotificationBar/>
          <Navbar/>
            {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  )
}
